name: Secret Demo

on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret
        run: echo "The secret is ${{ secrets.MY_SECRET_MESSAGE }}"
